version: '3.3'

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5431:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - my_network
    container_name: database

  fastapi:
    build: .
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - database
    networks:
      - my_network
    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

volumes:
  db_data:

networks:
  my_network:
    driver: bridge