"""update links table

Revision ID: 467bafd7e30c
Revises: dd447d77dc01
Create Date: 2025-03-16 21:54:12.677156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '467bafd7e30c'
down_revision: Union[str, None] = 'dd447d77dc01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('links_user_id_fkey', 'links', type_='foreignkey')
    op.drop_column('links', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('links_user_id_fkey', 'links', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
